apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server
  template: # Descreve como o POD deve ser criado
    metadata:
      labels:
        app: server
    spec:
      containers: # Especificação do container
      - name: server
        image: eliassv/hello-node:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
